---
" 0/食費":
- - 0/食費
  - 0
10/被服費:
- - 10/被服費
  - 10
20/生活費:
- - 20/生活費
  - 20
- - 21/電気ガス器具
  - 21
- - 22/IT製品
  - 22
30/医療費:
- - 30/医療費
  - 30
- - 31/化粧品
  - 31
40/電気ガス水道:
- - 40/電気
  - 40
- - 41/ガス
  - 41
- - 42/水道
  - 42
- - 43/電話
  - 43
- - 44/携帯電話
  - 44
- - 45/TV_net_新聞
  - 45
- - 49/misc
  - 49
50/教育費:
- - 50/教育費
  - 50
- - 51/仕送り
  - 51
60/交際費:
- - 60/交際費
  - 60
70/娯楽費:
- - 70/娯楽費
  - 70
- - 71/交通費
  - 71
- - 72/旅行費
  - 72
- - 73/ガソリン代
  - 73
80/車両費:
- - 80/車両費
  - 80
"その他":
- - 90/特別費
  - 90
- - 91/税金保険料
  - 91
