---
" 0/貯金":
- - 0/普通預金
  - 0
- - 1/定期預金
  - 1
- - 2/その他預金
  - 2
10/株・債券:
- - 10/株
  - 10
- - 11/債券
  - 11
- - 12/ETF他
  - 12
20/現金:
- - 20/現金
  - 20
30/固定資産:
- - 30/固定資産
  - 30
"その他":
- - 90/特別資産
  - 90
