# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39c1e67607e4b9e0fa7265ebf67d3daaa9c9233640fdf784fcab3b7d6fb518d5b282ac65406bd2dd3e313eee4ee448222196029d91cfe369855f71a103172580

test:
  secret_key_base: 2bcd20c529685d82f30a2785db0456f71f2ea3d1ca9a11e29ac71ff073fb51936da2f7435f70a07c99f7a17156a0d5802f80102261754f06cc80731f44b68ec0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 7cfeb826a6a3f5b27d237874eaa8acaa84f1acc683764624330059ac81977765021a72e9522fce5727058d2afbf779e11155d9ba42b3186b80612e4924038547
#  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
